<?php

namespace Database\Seeders;

use App\Models\RolePermission;
use Illuminate\Database\Seeder;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->defaultPermissions() as $permission) {
            RolePermission::updateOrCreate(
                ['permission_id' => $permission['permission_id']],
                $permission
            );
        }
    }

    private function defaultPermissions(): array
    {
        return [
            [
                'permission_id' => 'owner_dashboard',
                'menu_name' => 'Dashboard Owner',
                'menu_group' => 'owner',
                'path' => '/owner/dashboard',
                'icon' => '📊',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 1,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_reports',
                'menu_name' => 'Laporan Owner',
                'menu_group' => 'laporan',
                'path' => '/laporan',
                'icon' => '🧾',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 2,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_stocks',
                'menu_name' => 'Barang & Stok Owner',
                'menu_group' => 'stok',
                'path' => '/barang',
                'icon' => '📦',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 3,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_expenses',
                'menu_name' => 'Pengeluaran Owner',
                'menu_group' => 'pengeluaran',
                'path' => '/pengeluaran',
                'icon' => '💸',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 4,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_users',
                'menu_name' => 'Data User',
                'menu_group' => 'owner',
                'path' => '/owner/data-kasir',
                'icon' => '👥',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 5,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_login_activities',
                'menu_name' => 'Aktivitas Login',
                'menu_group' => 'owner',
                'path' => '/owner/aktivitas-login',
                'icon' => '🟢',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 6,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_role_permissions',
                'menu_name' => 'Role & Permission',
                'menu_group' => 'owner',
                'path' => '/owner/role-permission',
                'icon' => '🔐',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 7,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'owner_settings',
                'menu_name' => 'Pengaturan',
                'menu_group' => 'owner',
                'path' => '/pengaturan',
                'icon' => '⚙️',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => false,
                'sort_order' => 8,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'admin_dashboard',
                'menu_name' => 'Dashboard Admin',
                'menu_group' => 'admin',
                'path' => '/admin/dashboard',
                'icon' => '📈',
                'owner_access' => true,
                'admin_access' => true,
                'kasir_access' => false,
                'sort_order' => 9,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'admin_products',
                'menu_name' => 'Produk',
                'menu_group' => 'admin',
                'path' => '/admin/produk',
                'icon' => '📦',
                'owner_access' => true,
                'admin_access' => true,
                'kasir_access' => false,
                'sort_order' => 10,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'admin_stock_mutations',
                'menu_name' => 'Mutasi Stok',
                'menu_group' => 'stok',
                'path' => '/admin/mutasi',
                'icon' => '🔄',
                'owner_access' => true,
                'admin_access' => true,
                'kasir_access' => false,
                'sort_order' => 11,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'admin_stock_histories',
                'menu_name' => 'Riwayat Stok',
                'menu_group' => 'stok',
                'path' => '/admin/riwayat',
                'icon' => '🕘',
                'owner_access' => true,
                'admin_access' => true,
                'kasir_access' => false,
                'sort_order' => 12,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'admin_expenses',
                'menu_name' => 'Pengeluaran Cabang',
                'menu_group' => 'pengeluaran',
                'path' => '/pengeluaran',
                'icon' => '💰',
                'owner_access' => true,
                'admin_access' => true,
                'kasir_access' => false,
                'sort_order' => 13,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'cashier_pos',
                'menu_name' => 'POS / Transaksi',
                'menu_group' => 'kasir',
                'path' => '/',
                'icon' => '🧾',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => true,
                'sort_order' => 14,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'cashier_shift',
                'menu_name' => 'Shift Saya',
                'menu_group' => 'kasir',
                'path' => '/shift',
                'icon' => '🕒',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => true,
                'sort_order' => 15,
                'status' => 'Aktif',
            ],
            [
                'permission_id' => 'cashier_transactions',
                'menu_name' => 'Riwayat Transaksi',
                'menu_group' => 'kasir',
                'path' => '/transaksi',
                'icon' => '📜',
                'owner_access' => true,
                'admin_access' => false,
                'kasir_access' => true,
                'sort_order' => 16,
                'status' => 'Aktif',
            ],
        ];
    }
}
